"""create_otp_records_table

Revision ID: 0260664bc15b
Revises: 388fe08082d2
Create Date: 2026-07-06 10:22:41.184489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0260664bc15b'
down_revision: Union[str, None] = '388fe08082d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_records', sa.Column('hashed_phone', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_otp_records_hashed_phone'), 'otp_records', ['hashed_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_records_hashed_phone'), table_name='otp_records')
    op.drop_column('otp_records', 'hashed_phone')
    # ### end Alembic commands ###
