"""add_consents_and_access_logs

Revision ID: 23e181f7a9c4
Revises: ab3d7f897ebf
Create Date: 2026-07-08 16:21:52.532548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e181f7a9c4'
down_revision: Union[str, None] = 'ab3d7f897ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
