"""added_education_and_language_tables_updated_fields

Revision ID: 25589ad279d9
Revises: a1018cd84cf6
Create Date: 2026-07-13 16:59:39.303560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25589ad279d9'
down_revision: Union[str, None] = 'a1018cd84cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consents', 'user_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consents', sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
