"""Add is_deleted to Department and Position

Revision ID: 462411843e19
Revises: a64c68d31d83
Create Date: 2026-07-24 15:09:12.913145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462411843e19'
down_revision: Union[str, None] = 'a64c68d31d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('positions', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'is_deleted')
    op.drop_column('departments', 'is_deleted')
    # ### end Alembic commands ###
