"""add_social_links_to_candidate

Revision ID: 52084d570ee8
Revises: e18b511d6daa
Create Date: 2026-07-16 15:19:05.161426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52084d570ee8'
down_revision: Union[str, None] = 'e18b511d6daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
