"""add_social_links_to_candidate

Revision ID: 602124b7937b
Revises: 805f7a5c26cd
Create Date: 2026-07-16 15:41:08.613357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '602124b7937b'
down_revision: Union[str, None] = '805f7a5c26cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicants', 'social_links')
    # ### end Alembic commands ###
