"""add_hashed_phone_to_applicants

Revision ID: 7ba91156bf3d
Revises: ddc6eb0a7db0
Create Date: 2026-07-08 11:25:18.542668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba91156bf3d'
down_revision: Union[str, None] = 'ddc6eb0a7db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('hashed_phone', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_applicants_hashed_phone'), 'applicants', ['hashed_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applicants_hashed_phone'), table_name='applicants')
    op.drop_column('applicants', 'hashed_phone')
    # ### end Alembic commands ###
