"""create_failed_login_attempts_table

Revision ID: 7e77059e8bfa
Revises: f535b4f7d66d
Create Date: 2026-07-20 17:09:05.579671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e77059e8bfa'
down_revision: Union[str, None] = 'f535b4f7d66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
