"""add_social_links_to_candidate

Revision ID: 805f7a5c26cd
Revises: 1ae8f232c45c
Create Date: 2026-07-16 15:33:52.441650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805f7a5c26cd'
down_revision: Union[str, None] = '1ae8f232c45c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
