"""recreate_schema_with_extended_candidate_fields

Revision ID: a1018cd84cf6
Revises: 23e181f7a9c4
Create Date: 2026-07-13 15:14:05.088802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1018cd84cf6'
down_revision: Union[str, None] = '23e181f7a9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.String(length=50), nullable=False),
    sa.Column('school_name', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_educations_id'), 'candidate_educations', ['id'], unique=False)
    op.create_table('candidate_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_languages_id'), 'candidate_languages', ['id'], unique=False)
    op.add_column('applicants', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('applicants', sa.Column('nationality', sa.String(length=50), nullable=False))
    op.add_column('applicants', sa.Column('marital_status', sa.String(length=10), nullable=True))
    op.add_column('applicants', sa.Column('driving_license', sa.String(length=50), nullable=True))
    op.add_column('applicants', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('applicants', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('applicants', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('applicants', sa.Column('address_detail', sa.Text(), nullable=True))
    op.add_column('applicants', sa.Column('military_status', sa.String(length=20), nullable=True))
    op.add_column('applicants', sa.Column('skills', sa.Text(), nullable=True))
    op.drop_column('applicants', 'university')
    op.drop_column('applicants', 'graduation_year')
    op.drop_column('applicants', 'university_department')
    op.add_column('applications', sa.Column('experience_detail', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('cover_letter', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('reference_name', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('reference_position', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('reference_contact', sa.Text(), nullable=True))
    op.drop_column('applications', 'notes')
    op.add_column('consents', sa.Column('user_agent', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consents', 'user_agent')
    op.add_column('applications', sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('applications', 'reference_contact')
    op.drop_column('applications', 'reference_position')
    op.drop_column('applications', 'reference_name')
    op.drop_column('applications', 'cover_letter')
    op.drop_column('applications', 'experience_detail')
    op.add_column('applicants', sa.Column('university_department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('applicants', sa.Column('graduation_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('applicants', sa.Column('university', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('applicants', 'skills')
    op.drop_column('applicants', 'military_status')
    op.drop_column('applicants', 'address_detail')
    op.drop_column('applicants', 'district')
    op.drop_column('applicants', 'city')
    op.drop_column('applicants', 'gender')
    op.drop_column('applicants', 'driving_license')
    op.drop_column('applicants', 'marital_status')
    op.drop_column('applicants', 'nationality')
    op.drop_column('applicants', 'birth_date')
    op.drop_index(op.f('ix_candidate_languages_id'), table_name='candidate_languages')
    op.drop_table('candidate_languages')
    op.drop_index(op.f('ix_candidate_educations_id'), table_name='candidate_educations')
    op.drop_table('candidate_educations')
    # ### end Alembic commands ###
