"""rename_department_to_university_department

Revision ID: d0bacb935bd4
Revises: 0260664bc15b
Create Date: 2026-07-06 12:23:05.756379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0bacb935bd4'
down_revision: Union[str, None] = '0260664bc15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('university_department', sa.String(length=100), nullable=True))
    op.drop_column('applicants', 'department')
    op.alter_column('otp_records', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('otp_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_records', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('otp_records', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('applicants', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('applicants', 'university_department')
    # ### end Alembic commands ###
