"""make_candidate_fields_nullable_for_shadow_mode

Revision ID: e18b511d6daa
Revises: 6879734635e8
Create Date: 2026-07-16 11:15:28.218523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18b511d6daa'
down_revision: Union[str, None] = '6879734635e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applicants', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('applicants', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('applicants', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('applicants', 'hashed_phone',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('applicants', 'nationality',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applicants', 'nationality',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('applicants', 'hashed_phone',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('applicants', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('applicants', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('applicants', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
