"""feat(kvkk): add access log table for audit trails

Revision ID: f535b4f7d66d
Revises: 70c8fdb0472c
Create Date: 2026-07-20 14:45:44.816352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f535b4f7d66d'
down_revision: Union[str, None] = '70c8fdb0472c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
